---
output:
  pdf_document: default
  html_document: default
---

## Import libraries

```{r}
library(readxl)
library(ggplot2)
library(mgcv)
library(tidyverse)
ggplot2::theme_set(theme_classic())
options(repr.plot.width=15, repr.plot.height=7.5)
```

## Data cleaning

```{r}
# Read data
original_data <- read_excel("../data/Ametop-PE data(new-Alex)(1control 2study).xlsx")

# Save original_data for side effects analysis
data <- original_data

# Remove withdrawn patients
data <- data[data$`Withdrawn after consent?` != "Yes", ]

# Remove unnecessary variables
data <- select(data, 
               -`Elective surgery requiring IV?`,
               -`ASA I or II?`,
               -`Aged 5-16?`,
               -`Any allergies to Ametop, Pain Ease, or Tagederm adhesive?`,
               -`Ametop placed at least 30min before estimated IV start time?`,
               -`Receiving sedative pre-medication / anxiolytics?`,
               -`Needle phobia?`,
               -`Planned inhalation induction?`,
               -`Developmental delay or unable to interpret FPS-R?`,
               -`Time Ametop applied`,
               -`Time Ametop removed`,
               -`Time of skin puncture`,
               -`Record ID`,
               -`Complete?`,
               -`Withdrawn after consent?`,
               -`Reason for withdrawal`,
               -`Other reason for withdrawal`)
```

```{r}
# Check for missing values in all columns except 'Notes' and 'Observed side effects'
missing_values_summary <- data %>%
  select(-Notes, -`Observed side effects`) %>%
  summarise_all(~sum(is.na(.)))

# No missing values found
print(missing_values_summary)
```

```{r}
# Print rows with notes
# print(data[!is.na(data$Notes), ])

# Define keywords that suggest a mismatch between FPS-R score and observer score
# mismatch_keywords <- c("mischievous", "histrionic", "game", "understand scoring scale",
#                        "said ow", "did not feel", "dramatic")

# Create a pattern string to search for any of the keywords
# pattern <- paste(mismatch_keywords, collapse = "|")

# Use grep to find rows that match the pattern
# rows_to_exclude <- grep(pattern, data$Notes, ignore.case = TRUE)
# print(data[rows_to_exclude,])
# print(data[-rows_to_exclude,])
```

```{r}
# Shorten the data
data$`Reaction to skin puncture` <- gsub("^Slight.*", "Slight Pain", data$`Reaction to skin puncture`)
data$`Reaction to skin puncture` <- gsub("^Severe.*", "Severe Pain", data$`Reaction to skin puncture`)

# Verify the changes
table(data$`Reaction to skin puncture`)
```

## Data preprocessing

```{r}
# Create new variables 'Observer Number' for the dataset
data$`Observer Number` <- case_when(
  data$`Reaction to skin puncture` == "None" ~ 1,
  data$`Reaction to skin puncture` == "Slight Pain" ~ 2,
  data$`Reaction to skin puncture` == "Severe Pain" ~ 3
)
```

```{r}
# Verify data
head(data)
```

## Data analysis

```{r}
# Compare the sample sizes between the control group and the study group
table(data$Randomization)
```

# Histograms for FPS-R score
```{r}
data %>% 
    ggplot(aes(x = Age, y = `FPS-R score`)) +
    geom_point(size=4) +
    theme(text = element_text(size=25)) +
    scale_y_continuous(breaks=0:10) +
    labs(x = "Age",
         y = "FPS-R score")

# The younger the age, the more concentrated the distribution of pain scores.
```

```{r}
data %>% 
    ggplot(aes(x = Sex, y = `FPS-R score`)) +
    geom_point(size=4) +
    theme(text = element_text(size=25)) +
    scale_y_continuous(breaks=0:10) +
    labs(x = "Sex",
         y = "FPS-R score")
```

```{r}
data %>% 
    ggplot(aes(x = `Practitioner`, y = `FPS-R score`)) +
    geom_point(size=4) +
    theme(text = element_text(size=25)) +
    scale_y_continuous(breaks=0:10) +
    labs(x = "Practitioner",
         y = "FPS-R score")
```

```{r}
data %>% 
    ggplot(aes(x = `Number of IV attempts`, y = `FPS-R score`)) +
    geom_point(size=4) +
    theme(text = element_text(size=25)) +
    scale_y_continuous(breaks=0:10) +
    labs(x = "Number of IV attempts",
         y = "FPS-R score")
# The fewer the number of IV injections, the more concentrated the high pain scores are.
```

```{r}
data %>% 
    ggplot(aes(x = `Needle gauge`, y = `FPS-R score`)) +
    geom_point(size=4) +
    theme(text = element_text(size=25)) +
    scale_y_continuous(breaks=0:10) +
    labs(x = "Needle gauge",
         y = "FPS-R score")
```

# Linear model for FPS-R score
```{r}
# Linear model for FPS-R score
data$Sex <- as.factor(data$Sex)
data$Practitioner <- as.factor(data$Practitioner)
data$`Needle gauge` <- as.factor(data$`Needle gauge`)
linear_model <- lm(`FPS-R score` ~ Age + Sex + Practitioner + `Number of IV attempts` + `Needle gauge`
                   + Age * Sex + Age * `Number of IV attempts` + Age * Practitioner + Age * `Needle gauge`
                   + Sex * Practitioner + Sex * `Needle gauge` + `Needle gauge` * Practitioner + `Number of IV attempts` * Practitioner
                   , data = data)
summary(linear_model)
```

```{r}
# Plot linear model for FPS-R score
plot(linear_model)
```

# Pie chart for Observed side effects (No / Yes - Ametop alone / Yes - Ametop + vapocoolant spray)
```{r}
# Summarize "Any side effects observed?" column
side_effects_observed_summary <- table(
  ifelse(original_data$`Any side effects observed?` == "No", "No Side Effect",
         ifelse(original_data$Randomization == 1, "Side Effect (Ametop alone)",
                "Side Effect (Ametop + vapocoolant spray)"))
)

# Calculate percentages
percentages <- round(100 * side_effects_observed_summary / sum(side_effects_observed_summary), 1)

# Generate labels with percentages
labels <- paste(names(side_effects_observed_summary), " - ", percentages, "%", sep="")

# Pie Chart for "Any side effects observed?" with percentages
pie(side_effects_observed_summary,
    main = "Proportion of Patients with Any Observed Side Effects",
    col = rainbow(length(category_counts)),
    labels = labels,
    cex = 0.65)
```

# Pie chart for Observed side effects (Redness, Itching, Pain, Puffiness)
```{r}
# Filter out missing values and create a data frame with only the side effects
side_effects_data <- data.frame(SideEffects = na.omit(original_data$`Observed side effects`))

# Define the categorization function
categorize_effects <- function(effect) {
  effect_lower <- tolower(effect)
  categories <- list(
    Redness = "red|redness|pink",
    Itching = "itchy|pruritic|pruritis",
    Pain = "pain|painful",
    Puffiness = "puffy"
  )

  identified_categories <- character(0)

  # Negation patterns
  pattern_start <- "\\b(no|not)\\s+("
  pattern_middle <- ")\\b|(no|not)\\s+\\w+\\s+or\\s+("
  pattern_end <- ")"

  for (category_name in names(categories)) {
    symptom_pattern <- categories[[category_name]]

    # Check for the symptom but exclude if negated
    if (grepl(symptom_pattern, effect_lower)) {
      negation_pattern <- paste0(pattern_start, symptom_pattern, pattern_middle, symptom_pattern, pattern_end)
      if (!grepl(negation_pattern, effect_lower)) {
        identified_categories <- c(identified_categories, category_name)
      }
    }
  }

  # Return "Other" if no category is found
  if (length(identified_categories) == 0) {
    return("Other")
  }

  return(identified_categories)
}

# Apply the categorization function and create a list of categories for each side effect
side_effects_data$Categories <- sapply(side_effects_data$SideEffects, categorize_effects, USE.NAMES=FALSE)
print(data.frame(side_effects_data$SideEffects,
                 sapply(side_effects_data$Categories, paste, collapse = ", ")))

# Pie Chart 1
# Combination Categories
all_combination_categories <- sapply(side_effects_data$Categories, paste, collapse = " + ")

# Count the occurrences of each category
combination_category_counts <- table(all_combination_categories)

# Calculate the percentage for each category
combination_category_percentages <- round(combination_category_counts / sum(combination_category_counts) * 100, 1)

# Create labels that include both the category name and the percentage
combination_labels <- paste(names(combination_category_counts), " - ", combination_category_percentages, "%", sep="")

# Create a pie chart with percentages
pie(combination_category_counts,
    labels = combination_labels,
    main = "Combination Side Effects Distribution",
    col = rainbow(length(combination_category_counts)),
    cex = 0.8)

# Pie Chart 2
# Flatten the list into a vector
all_categories <- unlist(side_effects_data$Categories)

# Count the occurrences of each category
category_counts <- table(all_categories)

# Calculate the percentage for each category
percentages <- round(category_counts / sum(category_counts) * 100, 1)

# Create labels that include both the category name and the percentage
labels <- paste(names(category_counts), " - ", percentages, "%", sep="")

# Create a pie chart with percentages
pie(category_counts,
    labels = labels,
    main = "Individual Side Effects Distribution",
    col = rainbow(length(category_counts)),
    cex = 0.8)
```