---
title: "Objective 1"
output: pdf_document
date: "2024-02-20"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Data cleaning


```{r warning=FALSE}
library("readxl")
library(tidyverse)

#Upload data
data = read_excel("data/Ametop-PE data(new-Alex)(1control 2study).xlsx")

#Remove withdrawn patients
data <- data[data$`Withdrawn after consent?` != "Yes", ]

#Remove unnecessary variables
data <- select(data, 
               -`Elective surgery requiring IV?`,
               -`ASA I or II?`,
               -`Aged 5-16?`,
               -`Any allergies to Ametop, Pain Ease, or Tagederm adhesive?`,
               -`Ametop placed at least 30min before estimated IV start time?`,
               -`Receiving sedative pre-medication / anxiolytics?`,
               -`Needle phobia?`,
               -`Planned inhalation induction?`,
               -`Developmental delay or unable to interpret FPS-R?`,
               -`Time Ametop applied`,
               -`Time Ametop removed`,
               -`Time of skin puncture`,
               -`Record ID`,
               -`Complete?`,
               -`Reason for withdrawal`,
               -`Other reason for withdrawal`)


```

```{r}
# Check for missing values in all columns except 'Notes' and 'Observed side effects'
missing_values_summary <- data %>%
  select(-Notes, -`Observed side effects`) %>%
  summarise_all(~sum(is.na(.)))

#No missing values found
print(missing_values_summary)

```
```{r}
#Shorten the data
data$`Reaction to skin puncture` <- gsub(
  "^Slight.*", "Slight Pain", data$`Reaction to skin puncture`)

data$`Reaction to skin puncture` <- gsub(
  "^Severe.*", "Severe Pain", data$`Reaction to skin puncture`)

# Verify the changes
table(data$`Reaction to skin puncture`)
```


```{r}
# Creating new variables for the dataset

# Create 'Observer Number'
data$`Observer Number` <- case_when(
  data$`Reaction to skin puncture` == "None" ~ 1,
  data$`Reaction to skin puncture` == "Slight Pain" ~ 2,
  data$`Reaction to skin puncture` == "Severe Pain" ~ 3
)

# Create 'FPS-R Number'
data$`FPS-R Number` <- case_when(
  data$`FPS-R score` %in% c(0, 2) ~ 1,
  data$`FPS-R score` %in% c(4, 6) ~ 2,
  data$`FPS-R score` %in% c(8, 10) ~ 3
)

# 3. Create 'Match Responses'
data$`Match Responses` <- ifelse(data$`Observer Number` == data$`FPS-R Number`, "Yes", "No")
```

```{r}
#Verify data
head(data)
```
## Objective 1

```{r}

# Histogram
plot1 <- data %>% filter(Randomization == 1) %>%
  ggplot(aes(`FPS-R score`)) +
  geom_histogram() +
  labs(title = "Group 1 Histogram")

plot2 <- data %>% filter(Randomization == 2) %>%
  ggplot(aes(`FPS-R score`)) +
  geom_histogram() +
  labs(title = "Group 2 Histogram")

# Boxplot
plot3 <- data %>% filter(Randomization == 1) %>%
  ggplot(aes(`FPS-R score`)) +
  geom_boxplot() +
  labs(title = "Full Data Group 1 Boxplot")

plot4 <- data %>% filter(Randomization == 2) %>%
  ggplot(aes(`FPS-R score`)) +
  geom_boxplot() +
  labs(title = "Full Data Group 2 Boxplot")

# Boxplot
plot5 <- data %>% filter(Randomization == 1, `Match Responses` == "Yes") %>%
  ggplot(aes(`FPS-R score`)) +
  geom_boxplot() +
  labs(title = "Match Subset Data Group 1 Boxplot")

plot6 <- data %>% filter(Randomization == 2, `Match Responses` == "Yes") %>%
  ggplot(aes(`FPS-R score`)) +
  geom_boxplot() +
  labs(title = "Match Subset Data Group 2 Boxplot")

# Load the patchwork library
library(patchwork)

# Combine the plots
print("Group 1 = Control group \n Group 2 = Study group")
combined_plot <- (plot1 | plot2) / 
                 (plot3 | plot4) / 
                 (plot5 | plot6)
print(combined_plot)
```

```{r}
#Create a table to count matches
table <- table(data$`Observer Number`,data$`FPS-R Number`)

# Name the rows and columns to reflect the desired format
rownames(table) <- c("1", "2", "3")
colnames(table) <- c("1", "2", "3")


# Output the 3x3 table
cat("Contingency Table of FPS-R Number vs. Observer Number\n")
cat("Rows: FPS-R Number\n")
cat("Columns: Observer Number\n\n")
print(table)
```

```{r}
# T-test

# Perform t-test on full data
t_test_full <- t.test(data[data$Randomization == 1, ]$`FPS-R score`, 
                      data[data$Randomization == 2, ]$`FPS-R score`)
print(t_test_full)

#Perform t-test on subset of data
data_subset <- data[data$`Match Responses` == 'Yes',]
t_test_subset <- t.test(data_subset[data_subset$Randomization == 1, ]$`FPS-R score`, 
                        data_subset[data_subset$Randomization == 2, ]$`FPS-R score`)
print(t_test_subset)

# Conclusion: reject null on full data only, if match subset data (with 223-59=164 observations) we do not reject
```
